name: sac
channels:
  - pytorch
  # - conda-forge
  # - defaults
dependencies:
  - python=3.9
  - pytorch=1.12
  - pip=22.2.2
  - pip:
    - dill==0.3.6
    - einops==0.6.1
    - gym==0.25.2
    - moviepy==1.0.3
    - tensorboard==2.10.0